### ISSUE TITLE
group-by is not working properly

### ISSUE THREAD

**Issue by zeinab-zeitoun** [clojure-finance/clojask#59]
Hello,

I am using [com.github.clojure-finance/clojask "1.2.3"], but it seems that group-by is not functioning properly. 

I believe that the behavior of this function is not properly documented. I'm trying to run the examples you have in the documentation and this is the output:

My dataframe refers to Employees-example.csv that you provided as an example.
![image](https://user-images.githubusercontent.com/72575296/185755369-1f6dae52-313b-4a9a-8481-082ae975f710.png)

The output of (group-by x ["Salary"]) is:
![image](https://user-images.githubusercontent.com/72575296/185755393-013a4dfc-e1c3-4032-8cea-991bafd2f4b9.png)

The output of (ck/group-by x ["Employee" "EmployeeName" "Salary"]) is:
![image](https://user-images.githubusercontent.com/72575296/185755418-7f358e0d-f51b-4e8b-a126-80a7ad98c7d8.png)
The data under salary doesn't even refer to salaries data.

Is this the normal behavior of group-by? If not what am I doing wrong, and if yes, what's the value of group-by?

Thank you!

**Comment by hkulyc** [comment]
We have just released the latest version, 1.2.4-prerelease. Can you please confirm if this problem has been solved now? Thank you.

**Comment by zeinab-zeitoun** [comment]
@hkulyc thank you the problem has been solved now
