### ISSUE TITLE
rename-col does not work as expected

### ISSUE THREAD

**Issue by zeinab-zeitoun** [clojure-finance/clojask#60]
Hello!

I am using [com.github.clojure-finance/clojask "1.2.3"], and rename-col doesn't work as documented in  [https://clojure-finance.github.io/clojask-website/posts-output/API/#reorder-col--rename-col](https://clojure-finance.github.io/clojask-website/posts-output/API/#reorder-col--rename-col)

`(rename-col x ["Employee" "EmployeeName" "new-Department" "Salary"])` will result in:
Execution error (ArityException) at clojask-demo.core/eval48175 (form-init2877469409238441537.clj:61).
Wrong number of args (2) passed to: clojask.dataframe/rename-col

However, `(rename-col dataframe "Employee" "EmployeeNumber")` will work as expected.

The dataframe I'm referring to is 
![image](https://user-images.githubusercontent.com/72575296/185755912-c616cfeb-57c1-47e6-ad10-cb4587f68625.png)

Regards,

**Comment by hkulyc** [comment]
Thank you @zeinab-zeitoun for pointing this out. Sorry that we did not update the documentation to the latest version. We will update it ASAP.
