### ISSUE TITLE
Clojask aggregation execution error

### ISSUE THREAD

**Issue by zeinab-zeitoun** [clojure-finance/clojask#61]
Hello!

I am using `[com.github.clojure-finance/clojask "1.2.3"]` as a dependency and requiring the following namespaces:
`(:require [clojask.dataframe :as ck]
                [clojask.api.gb-aggregate :as gb-agg])`

The dataframe I'm using is Employees-example.csv with the following data:
![image](https://user-images.githubusercontent.com/72575296/185756233-56bc2618-9e62-4db4-9fc2-908e00acbd6f.png)

I'm running the following as per the documentation
`(ck/aggregate x gb-agg/max ["Salary"] ["Salary-max"])`

Yet, it's giving the following error:
`Execution error (OperationException) at clojask.dataframe.DataFrame/errorPredetect (dataframe.clj:388).
Failed in running operation: invalid arguments passed to aggregate function (original error: Wrong number of args (2) passed to: clojask.api.gb-aggregate/max)`

What am i doing wrong? 

Thank you in advance!

**Comment by zeinab-zeitoun** [comment]
requiring clojask.api.ggregate namespace results in 
```
java.io.FileNotFoundException
Could not locate clojask/api/ggregate__init.class,
clojask/api/ggregate.clj or clojask/api/ggregate.cljc on classpath.
```

**Comment by hkulyc** [comment]
Should be **`clojask.api.aggregate`**, thanks.

**Comment by zeinab-zeitoun** [comment]
oh sorry about that thank you!
